apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: prometheus-server
  name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
        kompose.image-pull-secret: regcred
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: prometheus-server
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_PROMETHEUS_SERVICE }}'
          name: prometheus-server
          ports:
            - containerPort: 9090
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
